version: 2
jobs:
    one:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run: "echo 1"
    two:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run: "echo 2"
    three:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run: "echo 3"
    four:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run: "echo 4"
    five:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run: "echo 5"

workflows:
    version: 2
    build:
        jobs:
            - one
            - two
            - three
            - four
            - five